import { Barber, Service, Review, GalleryImage, BlogPost } from "./types";

export const BARBERS: Barber[] = [
  {
    id: "1",
    name: "Marco",
    slug: "marco",
    role: "Master Barber",
    bio: "Marco has been cutting hair for over 12 years and is the founder of Maciel's. Known for his precision fades and old-school hot towel shaves, he brings a blend of classic technique and modern style to every cut.",
    specialties: ["Precision Fades", "Hot Towel Shave", "Classic Cuts"],
    photo: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&h=500&fit=crop&q=80",
    active: true,
    sortOrder: 1,
  },
  {
    id: "2",
    name: "Luis",
    slug: "luis",
    role: "Senior Barber",
    bio: "Luis specializes in modern fades and textured styles. His attention to detail and passion for the craft have made him one of our most requested barbers.",
    specialties: ["Modern Fades", "Textured Styles", "Beard Design"],
    photo: "https://images.unsplash.com/photo-1599351431613-18ef1fdd27e1?w=400&h=500&fit=crop&q=80",
    active: true,
    sortOrder: 2,
  },
  {
    id: "3",
    name: "Senor Caliente",
    slug: "senor-caliente",
    role: "Senior Barber",
    bio: "Senor Caliente brings energy and creativity to every chair. With a specialty in bold designs and skin fades, he delivers a personalized experience every time.",
    specialties: ["Skin Fades", "Hair Designs", "Color Work"],
    photo: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=500&fit=crop&q=80",
    active: true,
    sortOrder: 3,
  },
  {
    id: "4",
    name: "Andre",
    slug: "andre",
    role: "Barber",
    bio: "Andre is known for his calm demeanor and masterful scissors work. Whether it's a business cut or a laid-back weekend style, Andre delivers every time.",
    specialties: ["Scissors Work", "Business Cuts", "Kids Cuts"],
    photo: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=400&h=500&fit=crop&q=80",
    active: true,
    sortOrder: 4,
  },
  {
    id: "5",
    name: "Jose",
    slug: "jose",
    role: "Barber",
    bio: "Jose brings old-school New York barbershop tradition to every cut. Fast, clean, and always on point.",
    specialties: ["Tapers", "Lineups", "Classic Shaves"],
    photo: "https://images.unsplash.com/photo-1534308143481-c55f00be8bd7?w=400&h=500&fit=crop&q=80",
    active: true,
    sortOrder: 5,
  },
  {
    id: "6",
    name: "Victor",
    slug: "victor",
    role: "Barber",
    bio: "Victor rounds out the team with versatility across all hair types and styles. New to the crew but already a fan favorite.",
    specialties: ["All Hair Types", "Curly Hair", "Beard Shaping"],
    photo: "https://images.unsplash.com/photo-1570158268183-d296b2892211?w=400&h=500&fit=crop&q=80",
    active: true,
    sortOrder: 6,
  },
];

export const SERVICES: Service[] = [
  {
    id: "haircut",
    name: "Haircut",
    slug: "haircut",
    description:
      "Classic or modern cut tailored to your style. Includes a wash, cut, and style finish.",
    durationMinutes: 30,
    startingPrice: 25,
    active: true,
    category: "cut",
  },
  {
    id: "shave",
    name: "Shave",
    slug: "shave",
    description:
      "Traditional hot towel straight razor shave with pre-shave oil and aftershave balm.",
    durationMinutes: 30,
    startingPrice: 30,
    active: true,
    category: "shave",
  },
  {
    id: "combo",
    name: "Cut + Beard",
    slug: "combo",
    description:
      "The full package — haircut plus beard trim and shaping. Our most popular service.",
    durationMinutes: 60,
    startingPrice: 45,
    active: true,
    category: "combo",
  },
  {
    id: "beard-trim",
    name: "Beard Trim",
    slug: "beard-trim",
    description:
      "Clean up your beard with precision shaping, lining, and a hot towel finish.",
    durationMinutes: 20,
    startingPrice: 15,
    active: true,
    category: "beard",
  },
  {
    id: "kids-cut",
    name: "Kids Cut",
    slug: "kids-cut",
    description: "Clean cuts for the little ones (12 and under). Patient and gentle.",
    durationMinutes: 25,
    startingPrice: 18,
    active: true,
    category: "cut",
  },
  {
    id: "lineup",
    name: "Line Up",
    slug: "lineup",
    description:
      "Sharp edge-up along the hairline, sideburns, and neckline. Fast and fresh.",
    durationMinutes: 15,
    startingPrice: 12,
    active: true,
    category: "cut",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    reviewerName: "Carlos M.",
    rating: 5,
    body: "Best barbershop in New Rochelle, hands down. Marco gave me the cleanest fade I've had in years. The vibe is right, the cuts are sharp. Won't go anywhere else.",
    source: "Booksy",
    approved: true,
    publishedAt: "2024-11-12",
  },
  {
    id: "r2",
    reviewerName: "James T.",
    rating: 5,
    body: "Luis is incredible. He listened to exactly what I wanted and delivered. The shop is clean, the team is professional. 5 stars every time.",
    source: "Booksy",
    barberId: "2",
    approved: true,
    publishedAt: "2024-12-03",
  },
  {
    id: "r3",
    reviewerName: "David R.",
    rating: 5,
    body: "I've been going to Maciel's for two years. Consistent quality, every single time. Senor Caliente does my fades and I always leave looking fresh.",
    source: "Booksy",
    barberId: "3",
    approved: true,
    publishedAt: "2025-01-18",
  },
  {
    id: "r4",
    reviewerName: "Marcus L.",
    rating: 5,
    body: "Walked in on a Saturday afternoon, didn't have to wait long. Andre took care of me and the cut was perfect. Great atmosphere too.",
    source: "Booksy",
    barberId: "4",
    approved: true,
    publishedAt: "2025-02-07",
  },
  {
    id: "r5",
    reviewerName: "Tony V.",
    rating: 5,
    body: "My son gets his haircuts here and he loves Andre. Patient with kids and the cut always comes out great. Highly recommend for family.",
    source: "Google",
    approved: true,
    publishedAt: "2025-03-14",
  },
  {
    id: "r6",
    reviewerName: "Kevin S.",
    rating: 5,
    body: "Victor cut my hair for the first time last week and I was blown away. He nailed my curls perfectly. Will be back every two weeks.",
    source: "Booksy",
    barberId: "6",
    approved: true,
    publishedAt: "2025-04-02",
  },
];

export const GALLERY_IMAGES: GalleryImage[] = [
  {
    id: "g1",
    imageUrl: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80",
    altText: "Clean fade haircut",
    category: "haircut",
    approved: true,
    sortOrder: 1,
  },
  {
    id: "g2",
    imageUrl: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=80",
    altText: "Barber working on a client",
    category: "barber",
    approved: true,
    sortOrder: 2,
  },
  {
    id: "g3",
    imageUrl: "https://images.unsplash.com/photo-1599351431613-18ef1fdd27e1?w=800&q=80",
    altText: "Barbershop interior",
    category: "interior",
    approved: true,
    sortOrder: 3,
  },
  {
    id: "g4",
    imageUrl: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=80",
    altText: "Sharp lineup and beard trim",
    category: "haircut",
    approved: true,
    sortOrder: 4,
  },
  {
    id: "g5",
    imageUrl: "https://images.unsplash.com/photo-1534308143481-c55f00be8bd7?w=800&q=80",
    altText: "Classic barbershop tools",
    category: "detail",
    approved: true,
    sortOrder: 5,
  },
  {
    id: "g6",
    imageUrl: "https://images.unsplash.com/photo-1570158268183-d296b2892211?w=800&q=80",
    altText: "Finished haircut result",
    category: "haircut",
    approved: true,
    sortOrder: 6,
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "b1",
    title: "Best Men's Haircut Styles in New Rochelle",
    slug: "best-mens-haircut-styles-new-rochelle",
    excerpt:
      "Looking for the right cut? Here are the most popular styles our barbers in New Rochelle are delivering right now.",
    body: `New Rochelle has a strong barbershop culture, and the styles reflect that. From clean tapers to bold skin fades, here's what's trending at Maciel's right now.\n\n## The Skin Fade\nThe skin fade remains one of the most requested cuts. It tapers the sides down to the skin and creates a sharp, clean look that works for almost any hair type.\n\n## The Textured Crop\nPopular with younger clients, the textured crop keeps the top longer and messy while keeping the sides tight. Easy to style and low-maintenance.\n\n## The Classic Taper\nNever goes out of style. Clean on the sides, professional on top. Perfect for work environments.\n\n## The Comb Over Fade\nA modern take on the classic comb over. The fade keeps it fresh while the top length gives it character.`,
    featuredImage: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=1200&q=80",
    author: "Marco",
    category: "Style Guide",
    publishedAt: "2025-05-01",
    seoTitle: "Best Men's Haircut Styles in New Rochelle | Maciel's Barber Shop",
    seoDescription:
      "Explore the most popular men's haircut styles in New Rochelle — from skin fades to classic tapers — from the barbers at Maciel's.",
  },
  {
    id: "b2",
    title: "How Often Should You Get a Fade Cleaned Up?",
    slug: "how-often-get-fade-cleaned-up",
    excerpt:
      "The fade life requires maintenance. Here's how often you should be booking your next appointment.",
    body: `A fresh fade hits different. But how do you keep it looking sharp between visits?\n\n## Every 2 Weeks for Tight Fades\nIf you wear a skin fade or high tight fade, plan on coming in every 2 weeks. The contrast grows out fast and you'll notice it within 10 days.\n\n## Every 3-4 Weeks for Mid Fades\nA mid fade gives you a little more runway. Most clients with this style can go 3-4 weeks between cuts.\n\n## Monthly for Classic Tapers\nIf you rock a traditional taper, monthly cuts keep you looking clean without overdoing it.\n\n## Signs You Need to Book Now\n- The line between the fade and your natural hair is gone\n- Your neck hair is growing past the line\n- People stop complimenting your cut\n\nBook at Maciel's online any time — 24/7 booking available.`,
    featuredImage: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=1200&q=80",
    author: "Luis",
    category: "Grooming Tips",
    publishedAt: "2025-05-15",
    seoTitle: "How Often to Get a Fade Cleaned Up | Maciel's Barber Shop",
    seoDescription:
      "Not sure when to book your next fade? Maciel's barbers break down the ideal schedule by fade type.",
  },
  {
    id: "b3",
    title: "Beard Maintenance Basics Every Man Should Know",
    slug: "beard-maintenance-basics",
    excerpt:
      "A great beard doesn't maintain itself. Here are the fundamentals to keep yours looking its best.",
    body: `Growing a beard is easy. Keeping it looking intentional takes work. Here's the Maciel's guide to basic beard maintenance.\n\n## Trim Regularly\nEven if you're growing your beard out, trim it every 2-3 weeks to remove split ends and keep the shape clean.\n\n## Define Your Neckline\nA clean neckline makes a beard look intentional. The rule: draw a line from ear to ear following the natural curve about an inch above the Adam's apple. Everything below gets trimmed.\n\n## Use Beard Oil\nBeard oil moisturizes both the hair and skin underneath. Apply after a shower while the follicles are open. A few drops goes a long way.\n\n## Brush Daily\nA boar bristle brush trains beard hair and distributes oil evenly. 30 seconds in the morning makes a real difference.\n\n## Visit a Barber for Shape Work\nDIY beard maintenance is fine for maintenance, but come see us when you want to redefine your beard shape or try a new style.`,
    featuredImage: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=1200&q=80",
    author: "Senor Caliente",
    category: "Grooming Tips",
    publishedAt: "2025-06-01",
    seoTitle: "Beard Maintenance Basics | Maciel's Barber Shop New Rochelle",
    seoDescription:
      "Learn the basics of beard maintenance from the barbers at Maciel's Barber Shop in New Rochelle, NY.",
  },
];

export const HOURS = [
  { day: "Monday", hours: "9:00 AM – 7:00 PM" },
  { day: "Tuesday", hours: "9:00 AM – 7:00 PM" },
  { day: "Wednesday", hours: "9:00 AM – 7:00 PM" },
  { day: "Thursday", hours: "9:00 AM – 7:00 PM" },
  { day: "Friday", hours: "9:00 AM – 8:00 PM" },
  { day: "Saturday", hours: "8:00 AM – 6:00 PM" },
  { day: "Sunday", hours: "Closed" },
];

export const SHOP = {
  name: "Maciel's Barber Shop",
  address: "109 Union Ave, New Rochelle, NY 10801",
  phone: "(914) 000-0000",
  email: "info@macielsbarbershop.com",
  booksy: "https://booksy.com",
  instagram: "https://instagram.com",
  rating: 5.0,
  reviewCount: 21,
  mapUrl:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3009.!2d-73.78!3d40.91!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDDCsDU0JzM2LjAiTiA3M8KwNDYnNDguMCJX!5e0!3m2!1sen!2sus!4v1",
};
